# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).



Clearance.create(id: 1, name:"Admin")
Clearance.create(id: 2, name:"Management")
Clearance.create(id: 3, name:"Supervisor")
Clearance.create(id: 4, name:"Department Trainer")
Clearance.create(id: 5, name:"Record Managers")
Clearance.create(id: 6, name:"Boarding User")

Department.create(id: 1, name:"Security")
Department.create(id: 2, name:"Surveillance")
Department.create(id: 3, name:"IT/Audit")
Department.create(id: 4, name:"F & B")
Department.create(id: 5, name:"Finance")
Department.create(id: 6, name:"Hotel")
Department.create(id: 7, name:"Marketing/HR")
Department.create(id: 8, name:"EVS")
Department.create(id: 9, name:"Casino Operations")
Department.create(id: 10, name:"Facilities")

Incident.create(id: 1, name:"Intoxication")
Incident.create(id: 2, name:"Undesirable Activity")
Incident.create(id: 3, name:"Verbal Altercation")
Incident.create(id: 4, name:"Physical Altercation")
Incident.create(id: 5, name:"TITO Theft")
Incident.create(id: 6, name:"Property Theft")

Contype.create(id: 1, name: "Internal (Physical)")
Contype.create(id: 2, name: "Internal (Non-physical)")
Contype.create(id: 3, name: "External (Physical)")
Contype.create(id: 4, name: "External (Non-physical)")

Hour.create(id: 1, restaurant_name: "Horizon Buffet", monday: "11:30am-3:00pm", tuesday: "11:30am-3:00pm", wednesday: "11:30am-3:00pm", thursday: "11:30am-3:00pm", friday: "11:00am-3:00pm", saturday: "11:30am-3:00pm", sunday: "9:00am-3:00pm", secondary: "4:00pm-9:00pm")
Hour.create(id: 2, restaurant_name: "Pearl's Oyster Bar", monday: "Closed", tuesday: "Closed", wednesday: "Closed", thursday: "Closed", friday: "5:00pm-11:00pm", saturday: "4:00pm-11:00pm", sunday: "4:00pm-11:00pm", secondary: "")
Hour.create(id: 3, restaurant_name: "Amerisports", monday: "4:00pm-11:00pm", tuesday: "4:00pm-11:00pm", wednesday: "4:00pm-11:00pm", thursday: "4:00pm-11:00pm", friday: "3:00pm-1:00am", saturday: "11:00am-1:00am", sunday: "11:00am-10:00pm", secondary: "")
Hour.create(id: 4, restaurant_name: "Falcon Bakery", monday: "7:00am-2:00pm", tuesday: "7:00am-2:00pm", wednesday: "7:00am-2:00pm", thursday: "7:00am-2:00pm", friday: "7:00am-2:00pm", saturday: "7:00am-2:00pm", sunday: "7:00am-2:00pm", secondary: "")
Hour.create(id: 5, restaurant_name: "Great Plains", monday: "Closed", tuesday: "Closed", wednesday: "5:00pm-10:00pm", thursday: "5:00pm-10:00pm", friday: "5:00pm-10:00pm", saturday: "4:00pm-10:00pm", sunday: "5:00pm-10:00pm", secondary: "")
Hour.create(id: 6, restaurant_name: "Burger King", monday: "24/7", tuesday: "24/7", wednesday: "24/7", thursday: "24/7", friday: "24/7", saturday: "24/7", sunday: "24/7", secondary: "")
Hour.create(id: 7, restaurant_name: "Delilux", monday: "11:00am-3:00am", tuesday: "11:00am-3:00am", wednesday: "11:00am-3:00am", thursday: "11:00am-3:00am", friday: "11:00am-5:00am", saturday: "11:00am-5:00am", sunday: "11:00am-3:00am", secondary: "")
Hour.create(id: 8, restaurant_name: "HiVi Arcade", monday: "2:00pm-10:00pm", tuesday: "2:00pm-10:00pm", wednesday: "2:00pm-10:00pm", thursday: "2:00pm-10:00pm", friday: "12:00pm-10:00pm", saturday: "12:00pm-10:00pm", sunday: "11:00am-10:00pm", secondary: "")
Hour.create(id: 9, restaurant_name: "Star Club", monday: "12:00pm-11:00pm", tuesday: "12:00pm-11:00pm", wednesday: "12:00pm-11:00pm", thursday: "12:00pm-11:00pm", friday: "12:00pm-12:00am", saturday: "10:00am-12:00am", sunday: "10:00am-12:00am", secondary: "")
Hour.create(id: 10, restaurant_name: "Big Tony's Pizza", monday: "11:00am-12:00am", tuesday: "11:00am-12:00am", wednesday: "11:00am-12:00am", thursday: "11:00am-12:00am", friday: "11:00am-3:00am", saturday: "11:00am-3:00am", sunday: "11:00am-12:00am", secondary: "")
Hour.create(id: 11, restaurant_name: "Kid's Quest", monday: "2:00pm-11:00pm", tuesday: "2:00pm-11:00pm", wednesday: "2:00pm-11:00pm", thursday: "2:00pm-11:00pm", friday: "2:00pm-2:00am", saturday: "10:00am-2:00am", sunday: "11:00am-11:00pm", secondary: "")
Hour.create(id: 12, restaurant_name: "Regal Cinema", monday: "Varies", tuesday: "Varies", wednesday: "Varies", thursday: "Varies", friday: "Varies", saturday: "Varies", sunday: "Varies", secondary: "")
Hour.create(id: 13, restaurant_name: "Gift Shop", monday: "10:00am-9:00pm", tuesday: "10:00am-9:00pm", wednesday: "10:00am-9:00pm", thursday: "10:00am-9:00pm", friday: "10:00am-12:00am", saturday: "10:00am-12:00am", sunday: "10:00am-9:00pm", secondary: "")
Hour.create(id: 14, restaurant_name: "Falcon Diner", monday: "7:00am-1:00pm", tuesday: "7:00am-1:00pm", wednesday: "7:00am-1:00pm", thursday: "7:00am-1:00pm", friday: "7:00am-1:00pm", saturday: "7:00am-1:00pm", sunday: "7:00am-1:00pm", secondary: "")

Venue.create(id: 1, name: "Depot 9")
Venue.create(id: 2, name: "Star Pavilion")
Venue.create(id: 3, name: "Cabaret Bar")
Venue.create(id: 4, name: "Rendevouz Lounge")
Venue.create(id: 5, name: "Roadhouse")
Venue.create(id: 6, name: "Prairie Room")
Venue.create(id: 7, name: "Plateau Room")
Venue.create(id: 8, name: "Blackjack Tournement Area")
Venue.create(id: 9, name: "Poker Tournement Area")
Venue.create(id: 10, name: "Slots Tournement Area")
Venue.create(id: 11, name: "Patio Room")

Evetype.create(id: 1, name: "Live Entertainment")
Evetype.create(id: 2, name: "Private Event")
Evetype.create(id: 3, name: "Giveaway")
Evetype.create(id: 4, name: "Tournement")

Listing.create(location: "Main Boarding", department_id: 1, extension: "7047", phone_number: "816-414-7047")
Listing.create(location: "King Boarding", department_id: 1, extension: "7049", phone_number: "816-414-7049")
Listing.create(location: "West Boarding", department_id: 1, extension: "7087", phone_number: "816-414-7087")
Listing.create(location: "Team Boarding", department_id: 1, extension: "7026", phone_number: "816-414-7026")
Listing.create(location: "Surveillance", department_id: 2, extension: "7258", phone_number: "816-414-7258")

User.create(employee_num: "1379", first_name: "Boarding", last_name: "Officer", clearance_id: 6, department_id: 1, password: "1379")
User.create(employee_num: "12345", first_name: "John", last_name: "IT", clearance_id: 1, department_id: 3, password: "1234")
User.create(employee_num: "68117", first_name: "Colten", last_name: "Peterson", clearance_id: 4, department_id: 1, password: "1234")
User.create(employee_num: "69704", first_name: "Stewart", last_name: "Varner", clearance_id: 3, department_id: 1, password: "1234")
User.create(employee_num: "69293", first_name: "Debbie", last_name: "Needles", clearance_id: 3, department_id: 1, password: "1234")
User.create(employee_num: "33615", first_name: "Dale", last_name: "McGregor", clearance_id: 6, department_id: 1, password: "1234")
User.create(employee_num: "51875", first_name: "Mike", last_name: "Daniels", clearance_id: 6, department_id: 1, password: "1234")
User.create(employee_num: "34506", first_name: "Steven", last_name: "Gage", clearance_id: 6, department_id: 1, password: "1234")

Tip.create(id: 1, seeded: true, totd: "Follow department policy, don't allow non-security to dictate procedure")
Tip.create(id: 2, seeded: true, totd: "Be social, guests and team-members are social and are more likely to report problems if you present a friendly demeanor")
Tip.create(id: 3, seeded: true, totd: "Ignore the politics at work, your job is to ensure a safe environment")
Tip.create(id: 4, seeded: true, totd: "A clean, well-groomed appearance presents an approachable demeanor")
Tip.create(id: 5, seeded: true, totd: "Be vigilant at boarding, an officers worst enemy is complacency")
Tip.create(id: 6, seeded: true, totd: "Use your resources, never be afraid to ask a question")
Tip.create(id: 7, seeded: true, totd: "Most conflicts will be verbal, maintain your calm and level tone of voice to de-escalate the situation")
Tip.create(id: 8, seeded: true, totd: "Interact with the guests, ensure the guests of our presence for their safety")
Tip.create(id: 9, seeded: true, totd: "If you see a problem, do not ignore it contact your dispatcher")
Tip.create(id: 10, seeded: true, totd: "Be a problem solver, not the problem")
Tip.create(id: 11, seeded: true, totd: "You may have the solution no one has thought of, don't keep quiet.")
Tip.create(id: 12, seeded: true, totd: "Listen to your supervisors, they will guide you in the proper procedures")
Tip.create(id: 13, seeded: true, totd: "Aid your fellow officers, if you see them struggling don't ignore it, your team is only as strong as it's weakest link")
Tip.create(id: 14, seeded: true, totd: "It may be a slow day, but that is when you need to be your most vigilant")
Tip.create(id: 15, seeded: true, totd: "Walk the less traveled paths, trouble likes to be where it isn't seen")
Tip.create(id: 16, seeded: true, totd: "Be confident, not arrogant")
Tip.create(id: 17, seeded: true, totd: "Watch your surroundings, don't put yourself in a bad situation")
Tip.create(id: 18, seeded: true, totd: "Dictate the tempo of your interactions, don't let the guest direct you")
Tip.create(id: 19, seeded: true, totd: "Being punctual is key to an officers success")
Tip.create(id: 20, seeded: true, totd: "Know when guest service switches from the guest in front of you to the guests around you, don't get tunnel vision on helping a hostile guest")